/*
 * Install the Generative AI SDK
 *
 * $ npm install @google/generative-ai
 */

const {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} = require("@google/generative-ai");

const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
  model: "gemini-1.5-flash",
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxOutputTokens: 8192,
  responseMimeType: "application/json",
};

export  const chatSession = model.startChat({
    generationConfig,
    // safetySettings: Adjust safety settings
    // See https://ai.google.dev/gemini-api/docs/safety-settings
    history: [
      {
        role: "user",
        parts: [
          {
            text: "Write a script to generate 30 seconds video on topic :Interesting historical story along with AI image prompt in realistic formate for each scene and give me result in JSON formate with image prompt and content Text as field",
          },
        ],
      },
      {
        role: "model",
        parts: [
          {
            text: '## 30-Second Historical Video Script (JSON format)\n\n```json\n[\n  {\n    "image_prompt": "A bustling medieval marketplace, colorful stalls overflowing with goods, people in period clothing haggling and trading, sunlight streaming through the cobblestone streets.",\n    "content_text": "In the 14th century, a plague swept through Europe, killing millions. But amidst the chaos, a young woman named Agnes of Bohemia stood out. Agnes was a princess, but she dedicated her life to helping the sick and dying."\n  },\n  {\n    "image_prompt": "Agnes of Bohemia, a young woman with kind eyes and a determined expression, dressed in simple clothes, kneeling beside a sick person in a hospital bed, offering comfort.",\n    "content_text": "She established hospitals and orphanages, even risking her own life to care for those infected."\n  },\n  {\n    "image_prompt": "A montage of scenes depicting the plague: people collapsing in the streets, mass graves, empty houses, and medical staff in protective clothing struggling to help.",\n    "content_text": "The plague was brutal, but Agnes\'s compassion and courage inspired hope in a time of despair."\n  },\n  {\n    "image_prompt": "Agnes of Bohemia standing in front of a grand church, with a backdrop of a medieval city, her face glowing with a soft light, surrounded by grateful citizens.",\n    "content_text": "She became known as Saint Agnes, a symbol of resilience and love in the face of tragedy."\n  },\n  {\n    "image_prompt": "A close-up shot of a medieval book with an illustration of Agnes of Bohemia, the image slowly fades to black while the words \'Saint Agnes\' appear in elegant calligraphy.",\n    "content_text": "Her story reminds us that even in the darkest of times, humanity can find strength in compassion and selfless acts."\n  }\n]\n```\n\n**Explanation:**\n\n* This JSON format provides a structured script for a 30-second historical video about Saint Agnes of Bohemia.\n* Each object in the array represents a scene.\n* The "image_prompt" field contains a detailed description that can be used as input for an AI image generator to create the visuals.\n* The "content_text" field provides the narration for that scene.\n\n**To use this script:**\n\n1. Use the provided image prompts to generate images using an AI image generator like DALL-E 2, Midjourney, or Stable Diffusion.\n2. Assemble the generated images with the corresponding narration in a video editing software.\n3. Add music, sound effects, and transitions as needed to enhance the storytelling.\n\n**Note:** \n\n* The script is designed for a 30-second video, but it can be easily adapted to a different length.\n* The specific wording of the narration can be adjusted based on the desired tone and style of the video.\n* The images generated by the AI might need some post-processing to ensure they fit the overall theme and aesthetic of the video. \n',
          },
        ],
      },
    ],
  });

 
